create table profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique not null,
  display_name text,
  email text unique not null,
  avatar_url text,
  bio text default '',
  birth_date date,
  show_age boolean default false,
  country text,
  show_country boolean default false,
  created_at timestamptz default now()
);

alter table profiles enable row level security;

create policy "Perfiles visibles para todos los usuarios autenticados"
  on profiles for select
  to authenticated
  using (true);

create policy "Perfiles insertables solo por service_role"
  on profiles for insert
  to service_role
  with check (true);

create table audit_logs (
  id bigint generated by default as identity primary key,
  event text not null,
  user_id uuid references auth.users on delete set null,
  email text,
  ip text,
  user_agent text,
  metadata jsonb default '{}',
  timestamp timestamptz default now()
);

alter table audit_logs enable row level security;

create policy "Audit logs insertables solo por service_role"
  on audit_logs for insert
  to service_role
  with check (
    event is not null
    and (
      metadata is null
      or jsonb_typeof(metadata) = 'object'
    )
  );

create policy "Audit logs visibles solo por service_role"
  on audit_logs for select
  to service_role
  using (true);

create table friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users on delete cascade not null,
  receiver_id uuid references auth.users on delete cascade not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index idx_friend_requests_receiver on friend_requests(receiver_id, status);
create index idx_friend_requests_sender on friend_requests(sender_id, status);

create table followers (
  follower_id uuid references auth.users on delete cascade not null,
  following_id uuid references auth.users on delete cascade not null,
  created_at timestamptz default now(),
  primary key (follower_id, following_id)
);

alter table followers enable row level security;

create policy "Followers gestionables solo por service_role"
  on followers for all
  to service_role
  using (true)
  with check (true);

alter table friend_requests enable row level security;

create policy "Friend requests gestionables solo por service_role"
  on friend_requests for all
  to service_role
  using (true)
  with check (true);

create policy "Perfiles actualizables solo por service_role"
  on profiles for update
  to service_role
  using (true)
  with check (true);

-- Storage bucket for profile avatars
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 2097152, '{"image/png","image/jpeg","image/gif","image/webp"}')
on conflict (id) do nothing;

create policy "Avatars visibles para usuarios autenticados"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'avatars');

create policy "Avatars gestionables solo por service_role"
  on storage.objects for all
  to service_role
  using (bucket_id = 'avatars')
  with check (bucket_id = 'avatars');

create table chats (
  id uuid default gen_random_uuid() primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table chat_participants (
  chat_id uuid references chats on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  primary key (chat_id, user_id)
);

create index idx_chat_participants_user on chat_participants(user_id);

create table chat_messages (
  id bigint generated by default as identity primary key,
  chat_id uuid references chats on delete cascade not null,
  sender_id uuid references auth.users on delete cascade not null,
  content text not null,
  created_at timestamptz default now()
);

create index idx_chat_messages_chat on chat_messages(chat_id, created_at);

alter table chats enable row level security;
alter table chat_participants enable row level security;
alter table chat_messages enable row level security;

create policy "Chats gestionables solo por service_role"
  on chats for all
  to service_role
  using (true)
  with check (true);

create policy "Chat participants gestionables solo por service_role"
  on chat_participants for all
  to service_role
  using (true)
  with check (true);

create policy "Chat messages gestionables solo por service_role"
  on chat_messages for all
  to service_role
  using (true)
  with check (true);

alter table chat_participants add column last_read_at timestamptz default now();

create table username_changes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  old_username text not null,
  new_username text not null,
  created_at timestamptz default now()
);

create index idx_username_changes_user on username_changes(user_id, created_at);

alter table username_changes enable row level security;

create policy "Username changes gestionables solo por service_role"
  on username_changes for all
  to service_role
  using (true)
  with check (true);

create table notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  from_user_id uuid references auth.users on delete cascade not null,
  type text not null check (type in ('follow', 'friend_accept', 'friend_reject', 'unfollow', 'unfriend')),
  read boolean default false,
  created_at timestamptz default now()
);

create index idx_notifications_user on notifications(user_id, created_at desc);

alter table notifications enable row level security;

create policy "Notifications gestionables solo por service_role"
  on notifications for all
  to service_role
  using (true)
  with check (true);

create table posts (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null unique,
  content text not null check (char_length(content) <= 300),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index idx_posts_user on posts(user_id);

alter table posts enable row level security;

create policy "Posts gestionables solo por service_role"
  on posts for all
  to service_role
  using (true)
  with check (true);

create table post_likes (
  id bigint generated by default as identity primary key,
  post_id uuid references posts on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  created_at timestamptz default now(),
  unique (post_id, user_id)
);

create index idx_post_likes_post on post_likes(post_id);

alter table post_likes enable row level security;

create policy "Post likes gestionables solo por service_role"
  on post_likes for all
  to service_role
  using (true)
  with check (true);
