create table profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique not null,
  email text unique not null,
  created_at timestamptz default now()
);

alter table profiles enable row level security;

create policy "Perfiles visibles para todos los usuarios autenticados"
  on profiles for select
  to authenticated
  using (true);

create policy "Perfiles insertables solo por service_role"
  on profiles for insert
  to service_role
  with check (true);

create table audit_logs (
  id bigint generated by default as identity primary key,
  event text not null,
  user_id uuid references auth.users on delete set null,
  email text,
  ip text,
  user_agent text,
  metadata jsonb default '{}',
  timestamp timestamptz default now()
);

alter table audit_logs enable row level security;

create policy "Audit logs insertables solo por service_role"
  on audit_logs for insert
  to service_role
  with check (true);

create policy "Audit logs visibles solo por service_role"
  on audit_logs for select
  to service_role
  using (true);
